/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/AboutView': RouteRecordInfo<
      '/AboutView',
      '/AboutView',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/Admin': RouteRecordInfo<
      '/Admin',
      '/Admin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/HomeView': RouteRecordInfo<
      '/HomeView',
      '/HomeView',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/markdown/mddoc': RouteRecordInfo<
      '/markdown/mddoc',
      '/markdown/mddoc',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/test/dashboard': RouteRecordInfo<
      '/test/dashboard',
      '/test/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/test/nameview': RouteRecordInfo<
      '/test/nameview',
      '/test/nameview',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/AboutView.vue': {
      routes:
        | '/AboutView'
      views:
        | never
    }
    'src/admin/Admin.vue': {
      routes:
        | '/Admin'
      views:
        | never
    }
    'src/pages/HomeView.vue': {
      routes:
        | '/HomeView'
      views:
        | never
    }
    'src/markdown/mddoc.md': {
      routes:
        | '/markdown/mddoc'
      views:
        | never
    }
    'src/test/routes/dashboard.vue': {
      routes:
        | '/test/dashboard'
      views:
        | never
    }
    'src/test/routes/nameview@aux.vue': {
      routes:
        | '/test/nameview'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
